site_name: Essentials BES docs
plugins:
  - autolinks
  - search:
      lang: 
        - es
theme:
  name: material
  language: es
  palette:
    primary: deep orange
    accent: amber
  features:
    - content.code.annotate
    - search.suggest
    - search.highlight
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Introducción: "index.md"
  - Conceptos básicos:
    - Archivos de la carpeta raíz: ""
    - PBS: ""
    - Creación de tilesets: ""
  - Pokémon:
    - Definir Pokémon: "pokemon/DefPoke"
  - Batallas:
    - Movimientos:
      - Definir movimientos: "battles/DefineMovements"
    - Habilidades: ""
    - Tipos de batallas:
      - Entrenadores : "battles/Trainers"
      - Salvajes : ""
  - Objetos: ""
  - Mapas:
    - Definir un mapa: ""
    - Terrain tags: "maps/TerrainTags"
    - Estructuras: ""
  - Eventos:
    - Introducción a los eventos: "events/Introduction"
    - Interruptores y variables: "events/SwitchesAndVariables"
    - Eventos especiales: ""
  - Interfaces:
    - Interfaces Pokémon: ""
    - Interfaces del sistema: ""
  - Jugador:
    - Ajustes (Switches): ""
    - Cambiar aspecto: ""
    - Definir protagonistas: ""
  - Otros:
    - Settings (Ajustes): ""
    - Debug: ""
  - Tutoriales:
    - Crear nuevas etiquetas de terreno: "tutorials/CreatingTerrainTags"
  - Discord: "https://discord.com/invite/9XynJCM"
